<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>BasicConsole</RootNamespace>
    <AssemblyName>BasicConsole</AssemblyName>
    <StartupObject>BasicConsole.Program</StartupObject>
    <PreBuildEvent>if exist "$(TargetPath).locked" del "$(TargetPath).locked"
if exist "$(TargetPath)" if not exist "$(TargetPath).locked" move "$(TargetPath)" "$(TargetPath).locked"</PreBuildEvent>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyTitle>BasicConsole</AssemblyTitle>
    <Product>BasicConsole</Product>
    <Copyright>Copyright ©  2015</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DefineConstants>
    </DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="TracerLibrary">
      <HintPath>..\ThirdParty\Tracer\net452\TracerLibrary.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Altair\Altair.csproj" />
    <ProjectReference Include="..\BasicLibrary\BasicLibrary.csproj" />
  </ItemGroup>
</Project>