program = line , { line } ;
line = line_number , statement , { statement_separator , statement } , eol ;
line_number = digit , { digit } ;
digit = "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "0" ;
statement_separator = ":" ;
eol =  ( cr , lf ) | cr ;
number = integer | integer , "." , integer ;
integer = digit , { digit } ;
letter = "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z" | "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z" ;
character = letter | digit | symbol ;
symbol =  "|" | " " | "!" | "#" | "$" | "%" | "&" | "(" | ")" | "*" | "+" | "," | "-" | "." | "/" | ":" | ";" | "<" | "=" | ">" | "?" | "@" | "[" | "\" | "]" | "^" | "_" | "`" | "{" | "}" | "~" ;
statement = data_statement | def_statement | dim_statement | end_statement | for_statement | gosub_statement | goto_statement | if_statement | input_statement | let_statement | next_statement | on_statement | print_statement | read_statement | rem_statement | restore_statement | return_statement | stop_statement ;
data_statement = "DATA" , data_item , { separator , data_item } ;
data_item = number | string ;
def_statement = "DEF" , fn_function , "=" , expression ;
dim_statement = "DIM" , variable , "(" , integer , { separator , integer } , ")" , { separator , variable , "(" , integer , { separator , integer } , ")" } ;
end_statement = "END" ;
for_statement = "FOR" , numeric_variable , "=" , expression , "TO" , expression , [ "STEP" , expression ] ;
gosub_statement = "GOSUB" , line_number ;
goto_statement = "GOTO" , line_number ;
if_statement = "IF" , relation , ( "THEN" , ( line_number | statement ) | "GOTO" , line_number ) ;
input_statement = "INPUT" , variable , [ separator , variable ] ;
let_statement = [ "LET" ] , variable , "=" , expression ;
next_statement = "NEXT" , [ numeric_variable , { separator , numeric_variable } ] ;
on_statement = "ON" , expression , ( "GOTO" | "GOSUB" ) , line_number , { separator , line_number } ;
print_statement = "PRINT" , [ list , { ("," | ";") , list } ] ;
list = string | variable | expression | tab_function ;
read_statement = "READ" , variable , { separator , variable } ;
rem_statement = "REM" , [ remark ] ;
restore_statement = "RESTORE" ;
return_statement = "RETURN" ;
stop_statement = "STOP" ;
remark = { character } ;
relation = expression , relop , expression ;
relop = "<" | ">" | "=" | "<=" | ">=" | "<>" ;
variable = numeric_variable | string_variable ; 
numeric_variable = numeric_single_variable | numeric_array_variable ;
string_variable = string_single_variable | string_array_variable;
numeric_single_variable = letter , [digit] ; 
numeric_array_variable = letter , [digit] , "(" , expression , { separator , expression } , ")" ;
string_single_variable = letter , [digit] , "$"; 
string_array_variable = letter , [digit] , "$" , "(" , expression , { separator , expression } , ")" ;
expression = term , { addop , term } ;
addop = "+" | "-" ;
term = factor , { mulop , factor } ;
mulop = "*" | "/" ;
factor = number | string | variable | function | "(" , expression , ")" ;
function = sin_function | cos_function | tan_function | arctan_function | exponent_function | absolute_function | logarithm_function | square_root_function | fn_function | integer_function | random_function | sgn_function | usr_function | fre_function | inp_function | peek_function | pos_function | chr_function | left_function | len_function | mid_function | right_function | str_function | val_function  ;
separator = "," ;
string = quote , [ character , { character } ] , quote ;
quote = '"' ;	
sin_function = "SIN" , "(" , expression , ")" ;
cos_function = "COS" , "(" , expression , ")" ;
tan_function = "TAN" , "(" , expression , ")" ;
arctan_function = "ATN" , "(" , expression , ")" ;
exponent_function = "EXP" , "(" , expression , ")" ;
absolute_function = "ABS" , "(" , expression , ")" ;
logarithm_function = "LOG" , "(" , expression , ")" ;
square_root_function = "SQR" , "(" , expression , ")" ;
fn_function = "FN" , letter , "(" , variable , ")" ;
integer_function = "INT" , "(" , expression , ")" ;
random_function = "RND" , "(" , expression , ")" ;
sgn_function = "SGN" , "(" , expression , ")" ;
usr_function = "USR" , "(" , expression , ")" ;
fre_function = "FRE" , "(" , expression , ")" ;
inp_function = "INP" , "(" , expression , ")" ;
peek_function = "PEEK" , "(" , expression , ")" ;
pos_function = "POS" , "(" , expression , ")" ;
chr_function = "CHR" , "$" , "(" , expression , ")" ;
left_function = "LEFT" , "$" , "(" , expression , "," , expression , ")" ;
len_function = "LEN" , "(" , expression , ")" ;
mid_function = "MID" , "$" , "(" , expression , "," , expression , [ "," , expression ] , ")" ;
right_function = "RIGHT" , "$" , "(" , expression , "," , expression , ")" ;
str_function = "STR" , "$" , "(" , expression , ")" ;
val_function = "VAL" , "(" , expression , ")" ;
tab_function = "TAB" , "(" , expression , ")" ;
randomize_statement = "RANDOMIZE" ;







