<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0-windows7.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <SccProjectName>
    </SccProjectName>
    <SccLocalPath>
    </SccLocalPath>
    <SccAuxPath>
    </SccAuxPath>
    <SccProvider>
    </SccProvider>
    <PublishUrl>publish\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Disk</InstallFrom>
    <UpdateEnabled>false</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ApplicationRevision>0</ApplicationRevision>
    <ApplicationVersion>1.0.0</ApplicationVersion>
	  <Version>1.0.0</Version> <!-- General version -->
    <FileVersion>1.0.0.0</FileVersion> <!-- File version -->
    <AssemblyVersion>1.0.0.0</AssemblyVersion> <!-- Assembly version -->
    <Product>Basic</Product> <!-- Product name -->
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <UseApplicationTrust>false</UseApplicationTrust>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <DefineConstants>
    </DefineConstants>
    <StartupObject>BasicForm.Program</StartupObject>
    <ApplicationIcon>basic.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters" Version="2.0.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.8" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="MruMenuItem.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="properties\settings.designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Altair\Altair.csproj" />
    <ProjectReference Include="..\basicLibrary\basicLibrary.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="basic.ico" />
  </ItemGroup>
  <ItemGroup>
    <BootstrapperPackage Include=".NETFramework,Version=v4.5.2">
      <Visible>False</Visible>
      <ProductName>Microsoft .NET Framework 4.5.2 %28x86 and x64%29</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="TracerLibrary">
      <HintPath>..\ThirdParty\Tracer\net6.0\TracerLibrary.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <None Update="properties\settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
</Project>